### ISSUE TITLE
ssh-copy-id: ERROR: failed to open ID file 

### ISSUE THREAD

**Issue by gthvn1** [citrix-openstack/qa#84]
Hi,

 When I run the install-devstack-xen.sh script on my laptop I get the following error:

> Setup ssh keys on XenServer...
> /usr/bin/ssh-copy-id: ERROR: failed to open ID file '/tmp/tmp.LzXOB5ok0O/devstack': No such file or directory

It seems that to be able to do the copy the command ssh-copy-id needs to find the private key as devstack (it is based on devstack.pub). So on my system (I'm running archlinux 64bits) I need to copy the private key into the tmp dir. Here what I've done to solve the issue:

```
diff --git a/install-devstack-xen.sh b/install-devstack-xen.sh
index 2d81ee1..23052fe 100755
--- a/install-devstack-xen.sh
+++ b/install-devstack-xen.sh
@@ -158,6 +158,7 @@ function assert_tool_exists() {
 if [ -z "$JEOS_FILENAME" ]; then
     echo -n "Setup ssh keys on XenServer..."
     tmp_dir="$(mktemp -d)"
+    cp $PRIVKEY "$tmp_dir/devstack"
     ssh-keygen -y -f $PRIVKEY > "$tmp_dir/devstack.pub"
     assert_tool_exists sshpass
     sshpass -p "$XENSERVER_PASS" \
```

**Comment by VonChair** [comment]
So I ran into this same issue. I had a different step taken however. Allow me to outline the fix I found.
1. Running Pop OS 18.04
2. I copy my public key to a remote server using sudo ssh-copy-id -i .ssh/id_rsa.pub von@$ServerIP$
3. Works fine, but when I go to add additional keys to OTHER users on the server which I just set up, it gives the error of no such file.
4. Close this bash window and open another.
5. sudo ssh-copy-id -f -i .ssh/other_users/id_rsa.pub otheruser@$ServerIP$
This above command works only once I've opened a new bash session and closed the old one, so I think this issue still exists, but is tied to some arcane thing in the bash session it self on the local host.
